# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Build Artifact'
# - task: Maven@3
#   mavenPomFile: 'pom.xml'
#   mavenOptions: '-Xmx3072m'
#   javaHomeOption: 'JDKVersion'
#   jdkVersionOption: 'default'
#   jdkArchitectureOption: 'x64'
#   publishJUnitResults: true
#   testResultsFiles: '**/TEST-*.xml'
#   goals: 'package'

steps:
  # - task: JavaToolInstaller@0
  #   inputs:
  #     versionSpec: '17'
  #     jdkArchitecture: 'x64'

  - task: Maven@3
    inputs:
      mavenPomFile: 'todoapp-backend/pom.xml'
      goals: 'clean package -DskipTests'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
    displayName: 'Build Spring Boot'

  - script: |
      mkdir staging
      cp target/*.jar staging/backend/app.jar
      ls
    displayName: 'Prepare Deployment Artifact'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'staging'
      artifactName: '$(artifactName)'
  