# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package -DskipTests'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
    displayName: 'Build Spring Boot'

  - script: |
      mkdir -p staging/backend
      cp target/*.jar staging/backend/
    displayName: 'Prepare Deployment Artifact'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'staging'
      artifactName: '$(artifactName)'
  